### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by olmesm** [hamzahg/radio-test#2]
Hi Hamza - thanks for this!

Happy to give this feedback in person but this is a really well structured project and exactly what I would expect from a lead 👍 

- Readme's are often overlooked and you've kept is short and simple - thanks!
- haven't ever seen craco used before so it's cool to see that implemented (but IIRC I've also not done tailwind with CRA before so not sure if thats form some setup docs 😅)
- tooling is perfect and glad to see `.vscode` setup - there's also a `.vscode/.extensions.json` if you've never seen that before
- react hooks is sweet (no problem with class - but good to know you've got the exp)
- good to see aria tags used 

Thanks for the submission and looking forward to our chat!

**Comment by hamzahg** [comment]
Hey Oli, thanks for the feedback. 

Yep regarding using craco, I only started using it in my boilerplates a couple of weeks ago as before that getting tailwind working with CRA was an absolute pain - you'd have to eject and add it into the webpack config. Tailwind now recommend using it, which is definitely a much smoother experience - although only after setting it up did I spot that css frameworks weren't allowed for the test 🤦‍♂️ 

Chat to you on monday!
